#!/bin/bash
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "~~~~~~~~~~~~COMMANDES DISPONIBLES~~~~~~~~~~~"
echo "~~~~~~~~~~~~~~~~°DELETE°~~~~~~~~~~~~~~~~~~~~"
echo "~~Parametre~~~~~~~~~~~~ALL,TABLE,LIGNE~~~~~~"
echo "~~~~~ALL:supprime la BDD~~~~~~~~~~~~~~~~~~~~"
echo "~~~~~TABLE:supprime la table~~~~~~~~~~~~~~~~"
echo "~~~~~LIGNE:supprime la ligne qui commence~~~"
echo "~~~~~~~~~~~~~~~~°UPDATE°~~~~~~~~~~~~~~~~~~~~"
echo "~~Parametre~~~~~~~~~~~~ALL~~~~~~~~~~~~~~~~~~"
echo "~~~~~ALL:change le mot en un autre~~~~~~~~~~"
echo "~~~~~~~~~~~~~~~~~°END°~~~~~~~~~~~~~~~~~~~~~~"
echo "~~~~~Quitte l'invité de commande~~~~~~~~~~~~"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
read -p "Appuyer sur une touche pour continuer ..."
